import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Web3Modal from "web3modal";
import TOKEN_ABI from "../config/Token.json";
import config from "../config/config.json";

import { useEffect, useState } from "react";
import { ethers } from "ethers";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [currentAccount, setCurrentAccount] = useState("");
  const [name, setName] = useState("");
  const [symbol, setSymbol] = useState("");
  const [balance, setBalance] = useState("");
  const [inputAddress, setInputAddress] = useState("");
  const [inputValue, setInputValue] = useState("");

  const ConnectToWallet = async () => {
    try {
      if (!window.ethereum)
        return alert("Install a Wallet like MetaMask to connect");

      const accounts = await window.ethereum.request({
        method: "eth_accounts",
      });

      window.ethereum.on("accountsChanged", () => {
        window.location.reload();
      });

      if (accounts.length) {
        setCurrentAccount(accounts[0]);
      } else {
        alert("Wallet is not connected");
      }
    } catch (error) {
      setError("Wallet is not connected");
    }
  };

  const connectWallet = async () => {
    try {
      if (!window.ethereum)
        return alert("Install a Wallet like MetaMask to connect");

      const accounts = await window.ethereum.request({
        method: "eth_requestAccounts",
      });

      setCurrentAccount(accounts[0]);

      alert("Successfully Connected to Wallet");
    } catch (error) {
      alert("Error while connecting to Wallet");
      console.log(error);
    }
  };

  const fetchContract = async () => {
    try {
      const web3Modal = new Web3Modal();
      const connection = await web3Modal.connect();
      const provider = new ethers.BrowserProvider(connection);

      const { chainId } = await provider.getNetwork();

      const signer = await provider.getSigner();

      const tokenConfig = config[chainId].token;
      const tokenContract = new ethers.Contract(
        tokenConfig.address,
        TOKEN_ABI,
        signer
      );

      return tokenContract;
    } catch (error) {
      console.error(error);

      alert("Error fetching contract");
    }
  };

  const tokenName = async () => {
    const contract = await fetchContract();
    const data = await contract.name();
    setName(data);
  };

  const tokenSymbol = async () => {
    const contract = await fetchContract();
    const data = await contract.symbol();
    setSymbol(data);
  };

  const tokenBalance = async () => {
    const contract = await fetchContract();
    console.log(currentAccount);
    const data = await contract.balanceOf(currentAccount);
    console.log(parseInt(data));
    setBalance(parseInt(data));
  };

  const tokenMint = async () => {
    const contract = await fetchContract();
    const data = await contract.mint(inputAddress, inputValue);
    alert("Minted Successfully");
  };

  const tokenBurn = async () => {
    const contract = await fetchContract();
    const data = await contract.burn(inputAddress, inputValue);
    alert("Burn Successfully");
  };

  const handleMintSubmit = (event) => {
    event.preventDefault(); // Prevent form submission
    tokenMint();
    // Do something with the input values
    console.log("Input value 1:", inputAddress);
    console.log("Input value 2:", inputValue);
    // Add your custom logic here

    // Reset input field values
    setInputAddress("");
    setInputValue("");
  };

  useEffect(() => {
    try {
      ConnectToWallet();
      fetchContract();
      tokenName();
      tokenSymbol();
      if (currentAccount) {
        tokenBalance();
      }
    } catch (error) {
      console.error(error);
    }
  });

  return (
    <>
      <Head>
        <title>My Token</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <h1>
            <p>
              <code
                className={styles.code}
              >{` Balance ${balance} ${symbol}`}</code>
            </p>
          </h1>

          <div>
            {currentAccount == "" ? (
              <button className="btn" role="button" onClick={connectWallet}>
                Connect
              </button>
            ) : (
              <button className="btn" role="button">
                {currentAccount.substring(0, 5) +
                  "..." +
                  currentAccount.substring(
                    currentAccount.length - 5,
                    currentAccount.length
                  )}
              </button>
            )}
          </div>
        </div>

        <div className={styles.center}>
          <h1>Welcome to {!currentAccount ? "" : name}</h1>
        </div>

        <div className={styles.grid}>
          <form onSubmit={handleMintSubmit}>
            <input
              type="text"
              value={inputAddress}
              onChange={(e) => setInputAddress(e.target.value)}
              placeholder="Enter text 1"
            />
            <input
              type="number"
              value={inputValue}
              onChange={(e) => setInputValue(e.target.value)}
              placeholder="Enter text 2"
            />
            <button type="submit">Submit</button>
          </form>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Docs <span>-&gt;</span>
            </h2>
            <p>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Learn <span>-&gt;</span>
            </h2>
            <p>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Templates <span>-&gt;</span>
            </h2>
            <p>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Deploy <span>-&gt;</span>
            </h2>
            <p>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  );
}
